export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';

export const WATCH_EVENTS_GET = 'WATCH_EVENTS_GET';
export const WATCH_EVENTS_GET_SUCCESS = 'WATCH_EVENTS_GET_SUCCESS';
export const WATCH_EVENTS_GET_ERROR = 'WATCH_EVENTS_GET_ERROR';
export const WATCH_EVENTS_RESET = 'WATCH_EVENTS_RESET';

export const REPOSITORIES_SUCCESS = 'REPOSITORIES_SUCCESS';