export const USER_NAME_SET = 'USER_NAME_SET';
export const USER_TOKEN_RECEIVE = 'USER_TOKEN_RECEIVE';
export const USER_TOKEN_REQUEST = 'USER_TOKEN_REQUEST';
export const USER_TOKEN_ERROR = 'USER_TOKEN_ERROR';
export const USER_RESET = 'USER_RESET';
export const USER_INFO_RECEIVE = 'USER_INFO_RECEIVE';

export const WATCH_EVENTS_GET = 'WATCH_EVENTS_GET';
export const WATCH_EVENTS_GET_SUCCESS = 'WATCH_EVENTS_GET_SUCCESS';
export const WATCH_EVENTS_GET_ERROR = 'WATCH_EVENTS_GET_ERROR';
export const WATCH_EVENTS_RESET = 'WATCH_EVENTS_RESET';

export const REPOSITORIES_SUCCESS = 'REPOSITORIES_SUCCESS';
