export const SET_USER = 'SET_USER';

export const WATCH_EVENTS_GET = 'WATCH_EVENTS_GET';
export const WATCH_EVENTS_GET_SUCCESS = 'WATCH_EVENTS_GET_SUCCESS';
export const WATCH_EVENTS_GET_ERROR = 'WATCH_EVENTS_GET_ERROR';
export const WATCH_EVENTS_RESET = 'WATCH_EVENTS_RESET';
